app:
  name: ginblog
  env: local
  url: localhost:8080

jwt:
  secret: yahaha
  expire: 24
  issuer: ginblog

session:
  name: yh-session
  secret: yh-secret
  age: 3600

datasource:
  host: localhost
  port: 33066
  database: ginblog
  username: root
  password: 12345566

redis:
  db: 7
  addr: '127.0.0.1:63799'
  password: '66554321'